language: node_js
node_js:
  - "0.10"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g grunt-cli karma bower
  - cd server
  - npm install
  - cd ../client
  - bower install
  - npm install
  - cd ..

script: make travis

